### ISSUE TITLE
请求收入OpenWHU项目

### ISSUE THREAD

**Issue by Crescentm** [yaoyue123/SocialComputing#1]
想把您的实验资料收集进OpenWHU项目，望批准❤
[项目地址](https://github.com/openwhu/OpenWHU)

**Comment by yaoyue123** [comment]
> 想把您的实验资料收集进OpenWHU项目，望批准❤
> [项目地址](https://github.com/openwhu/OpenWHU)

这门课程是网安院新开的课程，尚属于探索阶段，具体课程要求每年会有不同，若是收录可能会误导同学们

**Comment by Crescentm** [comment]
会把时间标注上的，主要是作为参考。（以及今年的平时作业也有电影评论极性分析😩）

**Comment by yaoyue123** [comment]
> 会把时间标注上的，主要是作为参考。（以及今年的平时作业也有电影评论极性分析😩）

好的，请收录吧

**Comment by Crescentm** [comment]
感谢学长，真的十分感谢
https://github.com/openwhu/OpenWHU/tree/master/%E4%B8%93%E4%B8%9A%E8%AF%BE/%E5%9B%BD%E5%AE%B6%E7%BD%91%E7%BB%9C%E5%AE%89%E5%85%A8%E5%AD%A6%E9%99%A2/%E7%A4%BE%E4%BC%9A%E8%AE%A1%E7%AE%97/%E5%AE%9E%E9%AA%8C%E4%BD%9C%E4%B8%9A/2018%E7%BA%A7
